name: Testing Jython
on:
  push:
    branches:
      - main
jobs:
  prepare:
    runs-on: ubuntu-latest
    container: darkwingduck48/jython:latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: jython ./tests.py
      
        
