name: Testing Jython
on:
  push:
    branches:
      - main
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update ubuntu
        run: apt update
      - name: Install Jython
        run: apt install jython -y
      - name: Run tests
        run: jython ./tests.py
      
        
